---

# - hosts: MONGODB_PRIMARY
  # roles:
   # - { role: role-mongodb-primary,   
       # mongodb_work_path: /home/core/mongo,
       # mongodb_deploy_config: true,
       # mongo_admin_user: siteAdmin,
       # mongo_admin_pass: admin,
       # mongo_db_name: soc-db,
       # mongo_root_user: siteRoot, 
       # mongo_root_pass: root
     # }

- hosts: NODEJS_API
  roles:
   - { role: role-nodejs-api,
       nodejs_deploy_config: true,
       nodejs_work_path: /home/core,
       soc_api_logpath: /var/log/soc-api,
       mongodb_ip_address: "{{ groups['MONGODB_PRIMARY'][0] }}",
       soc_api_version: v1.2.0
     }