---

- hosts: MONGODB_PRIMARY
  roles:
   - { role: role-mongodb-primary, 
       mongodb_work_path: /home/core, 
       mongodb_node1_ip_address: "{{ groups['MONGODB_PRIMARY'][0] }}", 
       mongodb_node2_ip_address: "{{ groups['MONGODB_SECONDARY'][0] }}", 
       mongodb_deploy_config: true, 
       mongo_admin_user: siteAdmin, 
       mongo_admin_pass: admin, 
       mongo_root_user: siteRoot, 
       mongo_root_pass: root, 
       dockerfile_repository: "https://github.com/oudomsieng/mongodb-docker.git"
	 }

- hosts: MONGODB_SECONDARY
  roles:
   - { role: role-mongodb-secondary,
       mongodb_work_path: /home/core, 
       mongodb_node1_ip_address: "{{ groups['MONGODB_PRIMARY'][0] }}", 
       mongodb_node2_ip_address: "{{ groups['MONGODB_SECONDARY'][0] }}", 
       mongodb_deploy_config: true, 
       dockerfile_repository: "https://github.com/oudomsieng/mongodb-docker.git"
     }