---

- include: initialize-mongo-directory.yml

- name: Copy keyfile from local box to node2
  copy: src="{{ temporary_directory }}/mongodb-keyfile" dest="{{ mongodb_work_path }}/mongo-files/mongodb-keyfile" owner=999 mode=600
  become: yes
  
- include: remove-mongo-container.yml

- include: rebuild-mongo-image.yml

- name: Relaunch mongo container with replica set config
  command: docker run --name {{ mongo_container_name }} -v "{{ mongodb_work_path }}/mongo-files":/opt/keyfile -v "{{ mongodb_work_path }}/data":/data/db -v "{{ mongodb_work_path }}/log":/var/log/mongodb --hostname=\"{{ node2_hostname }}\" --add-host {{ node1_hostname }}:{{ mongodb_node1_ip_address }} --add-host {{ node2_hostname }}:{{ mongodb_node2_ip_address }} -p 27017:27017 -d {{ mongo_image_name }} mongod --config /etc/final-mongod.conf
  become: yes
