---

- name: Checking if ansible_distribution_major_version and ansible_distribution are not defined
  fail:
    msg: "Ansible distribution or ansible distribution version are not defined"
  when: ansible_distribution_major_version is not defined or ansible_distribution is not defined

- name: Checking if target server is not CentOS 7
  fail:
    msg: "This role can only be run on CentOS 7 servers"
  when: ansible_distribution != "CentOS" or (ansible_distribution == "CentOS" and ansible_distribution_major_version != "7")

- name: test input vars
  assert: { that: "{{ item }} is defined" }
  with_items:
      - nodejs_work_path
      - soc_api_version
      - dockerfile_repository
      - soc_api_logpath
      - mongodb_node1_ip_address
      - mongodb_node2_ip_address
  when: nodejs_deploy_config

- include: remove-nodejs-container.yml
  
- name: Delete nodejs working diectory
  file: 
    path: "{{ nodejs_work_path }}"
    state: absent
  become: yes

- name: Recreate nodejs working diectory
  file: 
    path: "{{ nodejs_work_path }}"
    owner: root
    group: root
    state: directory
    mode: 0777
  become: yes

- name: Create nodejs logging diectory if not exist
  file: 
    path: "{{ soc_api_logpath }}"
    owner: root
    group: root
    state: directory
    mode: 0777
  become: yes

- include: rebuild-nodejs-container.yml
  when: rebuild_docker_image

- name: git checkout soc-api
  git: 
    repo: https://oudomsieng@bitbucket.org/soc-gen/soc-api.git
    dest: "{{ nodejs_work_path }}/soc-api"
    version: "{{ soc_api_version }}"

- name: infrastructure config for app
  template:
    src: infra-prod.json.j2
    dest: "{{ nodejs_work_path }}/soc-api/config/infra-prod.json"

- name: Install nodejs project dependencies
  npm:
    production: yes
    path: "{{ nodejs_work_path }}/soc-api"

- name: Run nodejs container
  command: docker run --name {{ nodejs_container_name }} -v "{{ nodejs_work_path }}/soc-api":/usr/src/soc-api -v "{{ soc_api_logpath }}":/var/log/soc-api --hostname=\"{{ nodejs_api_hostname }}\" -p 8000:8000 -d {{ nodejs_image_name }} node index.js --logPath=/var/log/soc-api/
  become: yes
  